=== tomerguttman/SDMarket/SDM-V1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="super-duper-market-descriptor">
		<xs:complexType>
			<xs:all>
				<xs:element ref="SDM-items"/>
				<xs:element ref="SDM-stores"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="purchase-category">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Quantity"/>
				<xs:enumeration value="Weight"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="location">
		<xs:complexType>
			<xs:attribute name="y" type="xs:int" use="required"/>
			<xs:attribute name="x" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="delivery-ppk" type="xs:int"/>
	<xs:element name="SDM-stores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SDM-store" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SDM-store">
		<xs:complexType>
			<xs:all>
				<xs:element ref="name"/>
				<xs:element ref="delivery-ppk"/>
				<xs:element ref="location"/>
				<xs:element ref="SDM-prices"/>
			</xs:all>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SDM-sell">
		<xs:complexType>
			<xs:attribute name="price" type="xs:int" use="required"/>
			<xs:attribute name="item-id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SDM-prices">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SDM-sell" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SDM-items">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SDM-item" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SDM-item">
		<xs:complexType>
			<xs:all>
				<xs:element ref="name"/>
				<xs:element ref="purchase-category"/>
			</xs:all>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tomerguttman/SDMarket/Console/tests/ex1-big.xml
<?xml version="1.0" encoding="UTF-8"?>
<super-duper-market-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\aviad\courses\JAVAAN~1\exercises\2020-C~1\SAMPLE~1\ex1\SDM-V1.xsd">
	<SDM-items>
		<SDM-item id="1">
			<name>Toilet Paper</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="2">
			<name>Banana</name>
			<purchase-category>Weight</purchase-category>
		</SDM-item>
		<SDM-item id="3">
			<name>Lemon</name>
			<purchase-category>Weight</purchase-category>
		</SDM-item>
		<SDM-item id="4">
			<name>Pasta</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="5">
			<name>Tomato</name>
			<purchase-category>Weight</purchase-category>
		</SDM-item>
		<SDM-item id="6">
			<name>MIlki</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="7">
			<name>Eggs</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="8">
			<name>Candle</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="9">
			<name>Yellow Cheeze</name>
			<purchase-category>Weight</purchase-category>
		</SDM-item>
		<SDM-item id="10">
			<name>Yellow Cheeze</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
	</SDM-items>
	<SDM-stores>
		<SDM-store id="1">
			<name>Rami</name>
			<delivery-ppk>10</delivery-ppk>
			<location x="3" y="4"/>
			<SDM-prices>
				<SDM-sell item-id="1" price="10"/>
				<SDM-sell item-id="2" price="15"/>
				<SDM-sell item-id="5" price="3"/>
				<SDM-sell item-id="3" price="5"/>
				<SDM-sell item-id="9" price="6"/>
				<SDM-sell item-id="7" price="73"/>
			</SDM-prices>
		</SDM-store>
		<SDM-store id="2">
			<name>Hakol beshekel</name>
			<delivery-ppk>0</delivery-ppk>
			<location x="1" y="5"/>
			<SDM-prices>
				<SDM-sell item-id="2" price="1"/>
				<SDM-sell item-id="3" price="1"/>
				<SDM-sell item-id="4" price="1"/>
				<SDM-sell item-id="10" price="1"/>
				<SDM-sell item-id="6" price="1"/>
				<SDM-sell item-id="8" price="1"/>
			</SDM-prices>
		</SDM-store>
		<SDM-store id="3">
			<name>Benny Bannana</name>
			<delivery-ppk>10</delivery-ppk>
			<location x="45" y="34"/>
			<SDM-prices>
				<SDM-sell item-id="10" price="12"/>
				<SDM-sell item-id="5" price="14"/>				
				<SDM-sell item-id="1" price="51"/>
			</SDM-prices>
		</SDM-store>
		<SDM-store id="4">
			<name>Menashe Hagadol</name>
			<delivery-ppk>7</delivery-ppk>
			<location x="12" y="35"/>
			<SDM-prices>
				<SDM-sell item-id="2" price="10"/>
				<SDM-sell item-id="4" price="20"/>
				<SDM-sell item-id="6" price="30"/>
				<SDM-sell item-id="8" price="40"/>
				<SDM-sell item-id="10" price="50"/>				
			</SDM-prices>
		</SDM-store>
		
	</SDM-stores>
</super-duper-market-descriptor>

=== tomerguttman/SDMarket/Console/ex1-small.xml
<?xml version="1.0" encoding="UTF-8"?>
<super-duper-market-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\aviad\courses\JAVAAN~1\exercises\2020-C~1\SAMPLE~1\ex1\SDM-V1.xsd">
	<SDM-items>
		<SDM-item id="1">
			<name>Ketshop</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="2">
			<name>Banana</name>
			<purchase-category>Weight</purchase-category>
		</SDM-item>
		<SDM-item id="3">
			<name>Water</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="4">
			<name>Pasta</name>
			<purchase-category>Quantity</purchase-category>
		</SDM-item>
		<SDM-item id="5">
			<name>Tomato</name>
			<purchase-category>Weight</purchase-category>
		</SDM-item>
	</SDM-items>
	<SDM-stores>
		<SDM-store id="1">
			<name>super baba</name>
			<delivery-ppk>30</delivery-ppk>
			<location x="3" y="4"/>
			<SDM-prices>
				<SDM-sell item-id="1" price="20"/>
				<SDM-sell item-id="2" price="10"/>
				<SDM-sell item-id="5" price="50"/>
			</SDM-prices>
		</SDM-store>
		<SDM-store id="2">
			<name>Givataim Shivataim</name>
			<delivery-ppk>20</delivery-ppk>
			<location x="1" y="5"/>
			<SDM-prices>
				<SDM-sell item-id="2" price="20"/>
				<SDM-sell item-id="3" price="10"/>
				<SDM-sell item-id="4" price="50"/>
			</SDM-prices>
		</SDM-store>
	</SDM-stores>
</super-duper-market-descriptor>
